const state={token:"",selected:null,unit:null,concept:"ohms-law",openId:null,requestId:0};
const $=(selector,root=document)=>root.querySelector(selector);
async function api(path,options={}){const response=await fetch(path,options);const body=await response.json();if(!response.ok)throw new Error(body.error??"Request failed");return body;}
function message(text,error=false){const element=$("#message");element.textContent=text;element.className=error?"error":"success";}
function statusText(record){if(!record)return"Not reviewed / ยังไม่ได้ตรวจ";return`${record.review_status} · ${record.reviewer} · ${new Date(record.reviewed_at).toLocaleString()}`;}
function showPreview(){const area=$(".preview");if(!area)return;area.hidden=!$("#preview-toggle").checked;const content=$(".preview-content");content.replaceChildren();
  const step=(title,text)=>{const section=document.createElement("div");section.className="preview-step";const heading=document.createElement("h4");heading.textContent=title;const body=document.createElement("pre");body.textContent=text;section.append(heading,body);content.append(section);};
  step("1. Source evidence",`${state.unit.locator.chapter} → ${state.unit.locator.section}\n${state.unit.locator.document}`);
  const verified=state.unit.assets.filter(asset=>asset.kind==="math_image"&&asset.review?.review_status==="verified");
  step("2. Verified equations",verified.length?verified.map(asset=>`${asset.review.latex}\n${asset.review.plain_text}`).join("\n\n"):"ยังไม่มีสมการที่ผู้ตรวจยืนยันใน unit นี้");
  const proposals={"electric-current":"กระแสไฟฟ้าเป็นอัตราการไหลของประจุผ่านจุดหนึ่งของวงจร ใช้หน่วยแอมแปร์และระบุทิศทางที่กำหนดในการวิเคราะห์", "potential-difference":"ความต่างศักย์บอกพลังงานต่อหน่วยประจุระหว่างสองจุด ต้องระบุสองจุดที่วัดให้ชัดเจน", resistance:"ความต้านทานอธิบายความสัมพันธ์ระหว่างความต่างศักย์และกระแสของอุปกรณ์ ต้องตรวจเงื่อนไขอุณหภูมิและช่วงการทำงาน", "ohms-law":"สำหรับตัวนำโอห์มมิกที่อุณหภูมิและสภาพทางกายภาพคงที่ กระแสแปรผันตรงกับความต่างศักย์ ใช้สมการที่ตรวจแล้วด้านบนกับปริมาณของตัวนำเดียวกัน", "series-resistance":"ตัวต้านทานอนุกรมอยู่ในทางเดินกระแสเดียวกัน ตรวจแผนผังและจุดต่อก่อนใช้ความสัมพันธ์ของความต้านทานรวม", "parallel-resistance":"ตัวต้านทานขนานเชื่อมระหว่างจุดร่วมสองจุดและมีความต่างศักย์เท่ากัน ตรวจแขนงและหน่วยก่อนคำนวณ", "simple-circuit-topology":"แยกจุดร่วมและแขนงของวงจรจากภาพที่ผู้ตรวจยืนยันแล้ว ไม่ตัดสินการต่ออนุกรมหรือขนานจากตำแหน่งรูปเพียงอย่างเดียว", "simple-dc-circuit-analysis":"ระบุปริมาณที่ทราบในแต่ละส่วนของวงจร เลือกความสัมพันธ์ที่ใช้ได้ แล้วตรวจหน่วยและแทนคำตอบกลับ", "electrical-power":"กำลังไฟฟ้าเป็นอัตราการถ่ายโอนพลังงาน ใช้หน่วยวัตต์ ตรวจสมการและหน่วยให้ต่างจากพลังงาน", "electrical-energy":"พลังงานไฟฟ้าขึ้นกับช่วงเวลาที่มีการถ่ายโอนพลังงาน ใช้หน่วยจูลและแยกจากกำลังไฟฟ้าที่วัดเป็นวัตต์"};
  step("3. Proposed LearnlyAI knowledge section",`${proposals[state.concept]}\n\n${verified.length?"ใช้เฉพาะสมการที่มนุษย์ตรวจแล้วข้างต้นเป็นหลักฐานประกอบร่าง":"ยังรอสมการที่ตรวจแล้ว ไม่เติมหรือคาดเดาสมการจากภาพ"}\n\nข้อความเสนอโดย LearnlyAI · ยังไม่อนุมัติและไม่เผยแพร่เอกสาร`);
}
async function refreshList(){const query=new URLSearchParams({concept:state.concept});if(state.selected!==null)query.set("selected",[...state.selected].join(","));const data=await api(`/api/units?${query}`);if(state.selected===null)state.selected=new Set(data.units.filter(unit=>unit.selected).map(unit=>unit.id));
  const progress=data.progress;$("#progress").textContent=`${state.concept} · ${progress.reviewed} / ${progress.selected_assets} selected assets reviewed · ${progress.verified} verified · ${progress.needs_correction} need correction · ${progress.skipped} skipped`;
  $("#units").replaceChildren();for(const unit of data.units){const row=document.createElement("div");row.className="unit-row";const check=document.createElement("input");check.type="checkbox";check.checked=state.selected.has(unit.id);check.setAttribute("aria-label",`Select ${unit.title}`);check.addEventListener("change",async()=>{if(check.checked)state.selected.add(unit.id);else state.selected.delete(unit.id);try{await refreshList();}catch(error){message(error.message,true);}});
    const button=document.createElement("button");button.className="unit-open";button.textContent=unit.title;button.setAttribute("aria-current",String(unit.id===state.openId));const count=document.createElement("small");count.className="unit-count";count.textContent=`${unit.asset_count} assets`;button.append(count);button.addEventListener("click",()=>openUnit(unit.id).catch(error=>message(error.message,true)));row.append(check,button);$("#units").append(row);}
  return data;
}
async function openUnit(id){const requestId=++state.requestId;const unit=await api(`/api/units/${id}`);if(requestId!==state.requestId)return;state.unit=unit;state.openId=id;const detail=$("#detail");detail.replaceChildren($("#detail-template").content.cloneNode(true));$(".unit-title").textContent=unit.title;$(".chapter").textContent=unit.locator.chapter;$(".section").textContent=unit.locator.section;$(".document").textContent=unit.locator.document;$(".exact-locator").textContent=`${unit.source_id}\n${unit.artifact_id}\n${unit.locator.document}\n${unit.locator.chapter} → ${unit.locator.section}\n${unit.normalized_unit}`;
  // This is escaped/sanitized evidence generated by the local server, not raw EPUB HTML.
  $(".evidence").innerHTML=unit.evidence_html;
  for(const asset of unit.assets){const card=$("#asset-template").content.cloneNode(true);$(".asset-title",card).textContent=`${asset.kind==="math_image"?"Equation":"Diagram / image"} ${asset.index+1}`;$(".asset-image",card).src=asset.url;$(".asset-status",card).textContent=statusText(asset.review);$(".asset-locator",card).textContent=asset.archive_path;$(".latex",card).value=asset.review?.latex??"";$(".plain-text",card).value=asset.review?.plain_text??"";if(asset.kind!=="math_image")$(".latex-label",card).hidden=true;
    const element=$(".asset-card",card);for(const button of element.querySelectorAll("button[data-status]"))button.addEventListener("click",async()=>{const reviewer=$("#reviewer").value.trim();if(!reviewer){message("กรอกชื่อผู้ตรวจก่อนบันทึก / Enter reviewer name",true);$("#reviewer").focus();return;}const buttons=element.querySelectorAll("button");buttons.forEach(item=>item.disabled=true);try{const record=await api(`/api/reviews/${id}/${asset.index}`,{method:"POST",headers:{"Content-Type":"application/json","X-Review-Token":state.token},body:JSON.stringify({review_status:button.dataset.status,reviewer,latex:$(".latex",element).value,plain_text:$(".plain-text",element).value})});asset.review=record;$(".asset-status",element).textContent=statusText(record);await refreshList();showPreview();message("บันทึกผลตรวจแล้ว เอกสารยังไม่ได้อนุมัติ / Saved source review only");}catch(error){message(error.message,true);}finally{buttons.forEach(item=>item.disabled=false);}});
    $(".assets").append(card);}
  if(!unit.assets.length){const notice=document.createElement("p");notice.textContent="Unit นี้ไม่มีภาพสมการหรือแผนผัง";$(".assets").append(notice);}showPreview();await refreshList();}
$("#concept").addEventListener("change",async()=>{state.concept=$("#concept").value;state.selected=null;state.requestId++;try{const data=await refreshList();if(data.units.length)await openUnit(data.units.find(unit=>unit.selected)?.id??data.units[0].id);}catch(error){message(error.message,true);}});
$("#preview-toggle").addEventListener("change",showPreview);
async function start(){const bootstrap=await api("/api/bootstrap");state.token=bootstrap.token;for(const concept of bootstrap.concepts){const option=document.createElement("option");option.value=concept;option.textContent=concept;$("#concept").append(option);}$("#concept").value=state.concept;const data=await refreshList();if(data.units.length)await openUnit(data.units.find(unit=>unit.selected)?.id??data.units[0].id);}
start().catch(error=>message(error.message,true));
